version: 2

sources:
  - name: localbike_database
    schema: raw_localbike
    description: Données issues du système transactionnel de l’entreprise localbike
    tables:
      - name: customers
        description: Données client
      - name: stores
        description: Référentiel des magasins
      - name: staffs
        description: Données sur le personnel
      - name: orders
        description: Historique des commandes passées
      - name: order_items
        description: Détail des commandes
      - name: products
        description: Catalogue produits
      - name: categories
        description: Liste des catégories produits 
      - name: stocks
        description: Niveaux de stock disponibles par produit et par magasin
      - name: brands
        description: marques de produits localbike